[package]
name = "sshcmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
openssh = "0.9.0"
ssh2 = "0.9.3"
tokio = { version = "1.17.0", features = ["full"] }
