[package]
name = "notifywatch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.24"
notify = "5.0.0"
tokio = { version = "1.21.2", features = ["full"] }
lazy_static = "1.4.0"
