[package]
name = "toml-demo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "toml-demo"
path = "bin/main.rs"

[dependencies]
toml = "0.5.7"
serde = "1.0.117"
num_cpus = "1.13.0"